travis:
  secure:
    BINSTAR_TOKEN: X9mw8/mS232dhTviNFEQ7APNs+OZLQEaB4Urhw/FtKfHjcsWy+jK1xXB9GzJIHf+lCEnSN670KI0PXSrKbqVdysNS3/kwMRMOBreCF+p9YaY2UqrxAyeVbFd3cnKNb4jUE2YRrUEHR+eB09jEGeqWj7Wa7rJ1W+fMZg94d4GpxYqBbIwYVH8fzs7xDls0ZSTYWt3RhE18/8828svA6S+Ztwpe34xGT92+KMYn0IgKytZkPbu8Xjkl2lb1ud/P1CQjtMJiNzY1KchyP66eVJqJELjCixAqmBMN6zsPVnYeYHbXaLnby3aBNjQ3asTSzZYIVTRbPYw84a8gD2nRhpyykfPQx1CJ0kh0pktXlydi+qTj5BTxsTxJkJ6X+kzWjU2Z4MWMIOZ+/93br/ZuVHdUwgG3RyeIiOm7HxQfSOs6q42/tulnT6PAvpKDsj+W/GPuvmGuMaIVcdfAuXz8pSAqF5ZbtYSEAN5hS/d/wsaPJvn6aQ+tkBJNGfrZVIi4cPdIp+fOoxo6Dl3uAl/NUCg2upegWKz/08A3YAbMnLMvaZD5VxI4uZIQv9b1gOdcBLhUTrIVkmnsRILh1uc+o9AYAQupg0t1qee4UPKiR+DhmGbowXQMhKfuzmcvOxI84cabMRM0OEdA5gzAlGXlqFJU32awD4bkzNtPw8UxgqRiSg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
